### ISSUE TITLE
Formula: correct calculation of relative index (Kunst)

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#100]
@WHOequity Does the Excel workbook you provided (Inquequality measures (Sam Harper) - v1 - AS) have the right formulas and values for the riikm? Can I use that example to figure out what the issue is?

**Comment by WHOequity** [comment]
No, please refer to the formula in the word document I shared with you (different from the formula in the excel file).

**Comment by zross** [comment]
Have you implemented this one in Excel at all or only as a formula in Word. Do you have an example from our data that I can use to make sure I have it right?

**Comment by WHOequity** [comment]
No, unfortunately not. If you put it online, we can cross-check as well.

**Comment by zross** [comment]
I implemented the formula and tested against the example in the Word doc and it works for that one giving a value of 6.579 vs in the Word doc of 6.6.
