### ISSUE TITLE
Formula: use correct reference group in calculation of several measures

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#104]
use the correct reference group in the calculation of Mean Difference
from Best Performing Subgroup, Population Attributable Risk and
Population Attributable Fraction

**Comment by zross** [comment]
What should the correct reference group be? 

Currently MDB is::

if maximum optimum is 1 then the reference should be the maximum r value. Otherwise the reference should be the minimum r value.

Currently the par/paf rule is:

[if all of the rankorder values are > 0 AND any of the rankorder values are = 1 then set the reference to the r value with the highest rankorder value]

[otherwise if if there is a maximum optimum value (not 0) then the reference is the max r value otherwise it's the min r value.]

Note to myself, though: with MDB the maxopt is 0 or 1 but it's TRUE/FALSE for par/paf.

**Comment by WHOequity** [comment]
I think the formula for PAR/PAF is correct and should be applied to MDB as well: If the dimension is rankable (rankable=1) then use the most-advantaged group as the reference group (the group with the highest order number), regardless of the type of indicator (maxoptimum=0 or maxoptimum=1). If the dimension is not rankable (rankable=0), then use the subgroup with the maximum estimate as the reference group in the case of intervention indicators (maxoptimum=1) and use the subgroup with the minimum estimate as the reference group in the case of outcome indicators (maxoptimum=0).

**Comment by WHOequity** [comment]
Note that PAR/PAF should be calculated for all dimensions, but should be set to missing for non-rankable dimensions (rankable=0) if not all subgroup estimates are available. 

MDB should only be calculated for non-rankable dimensions with more than two subgroups.

**Comment by zross** [comment]
In the data you sent in Excel file with summary measures. MDB is only available for dimension = subnational region.

**Comment by WHOequity** [comment]
That's correct. BGV, MDB, MDM, MLD, IDIS, and TI are only calculated for "unrankable" dimensions with more than two subgroups as they can only be interpreted correctly for these dimensions (only subnational region in our database). 

On the contrary, ACI, RCI, SII, RII and RIIKM are only calculated for "rankable" dimensions with more than two subgroups.

**Comment by zross** [comment]
since my results match yours this is done
