### ISSUE TITLE
Formula: use national average in several measures

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#105]
use national average as provided in the Health Equity Monitor
database in the calculation of Between-Group Variance, Mean
Difference from Mean, Population Attributable Risk, Index of
Disparity, Mean Log Deviation, Population Attributable Fraction,
Relative Concentration Index, Relative Index of Inequality and Theil
Index.

**Comment by zross** [comment]
@WHOequity Were you finding that the national average was not being used in these? I'm seeing that for all but 3 (RCI, RII and Theil) the functions are set up to use the national average and seem to be using the national average.

**Comment by WHOequity** [comment]
There seemed to be inconsistencies in the use of national average between different summary measures. I think some of them are using national average as provided in the database, others are calculating national average based on the disaggregated data (which should only be done if the national estimate is not available, but data is available for all subgroups).

**Comment by zross** [comment]
This seems like how the functions are set up -- to use the national average if it's available and then to use a calculated national average based on disaggregated data otherwise -- I can check if it's not doing what it's supposed to be doing but can you point to an example of where this is not correct?

**Comment by WHOequity** [comment]
I will take a look at this.

**Comment by zross** [comment]
Actually, as I test the functions I can see ones that were "supposed" to be set up to use the national numbers have a switch that was set incorrectly. Am I right in assuming that you don't have examples of the correct estimates? It's hard to test if I've done the fix correctly without comparing to something.

**Comment by WHOequity** [comment]
We have done the calculations in Stata as well, but I think only for complete cases (i.e. observations where data is available for all subgroups and also for national average). This may still be helpful, though. I will prepare the material and share it with you.

**Comment by zross** [comment]
I've made the changes and all of these should use national averages but it would be good to compare results.

**Comment by zross** [comment]
we will need to compare but this is done
