### ISSUE TITLE
Formula: what happens with missing levels

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#106]
@WHOequity what is supposed to happen when one level is missing? It seems like the output is an NA but this is not explicitly mentioned in the code. Meaning, there is no "if a level is missing then return an NA". Is this what should be happening?

An example is: Albania, 2008, dhs, anc1, Education. One subgroup (No education) is missing data

**Comment by WHOequity** [comment]
Please show missing data in all tables. For disaggregated data, the flag indicates why estimates are missing. For summary measures, we should add an explanation at the top of the table ("Estimates for complex measures of inequality are missing if data for any population subgroup are missing").

**Comment by zross** [comment]
Just confirming that in calculating the inequality measures that if a level is missing the result should be an NA for all measures. Correct?

**Comment by zross** [comment]
@WHOequity Any chance you can answer this one? I'm still not clear. Should we be calculating summary measures if there is a missing level? What about missing `r`, `se` or `pop`? In the Albania example, you have values for `par` as an example, but I was setting the code to not compute summary measures if there is a missing level. How do you want it handled?

**Comment by zross** [comment]
Also is there special treatment of values=0? I'm seeing in `mld` that your Stata code and the R code do not match on treatment of `r=0`. You set to missing while the R code adds a small number to avoid taking log of 0. This skews the results. See #141

**Comment by WHOequity** [comment]
For missing disaggregated data, please see issue #93 (to be commented). 

For missing summary measure data, please see the word file I shared with you on Friday. Essentially: 
- RR and RD are set to missing if any subgroup estimate r that is required for the calculation (only two!) is missing
- PAR and PAF are set to missing
-- for "rankable dimensions": if any subgroup estimate r that is required for the calculation (only one!) is missing
-- for "non-rankable dimensions": if any subgroup estimate r is missing
- IDIS is set to missing to missing if any subgroup estimate r is missing
- All other measures (MDB, MDM, BGV, TI, MLD, SII, RII, RIIKM, ACI and RCI) are set to missing if any subgroup estimate r or any population share pop is missing

The standard error se is not relevant for the calculation of point estimates.

**Comment by WHOequity** [comment]
We don't have a special treatment of r=0 in our Stata codes. I will get back to you on this.

**Comment by zross** [comment]
In several places in the Summary measures - interventions 2015-05.do file you have something like:

`replace mld=. if rnonmissing==0	| pnonmissing==0`

I'm assuming this says if `r` or `p` is 0 replace with missing?

**Comment by WHOequity** [comment]
Correct. rnonmissing and pnonmissing are defined at the beginning of the do-file: 

rnonmissing is a dummy variable that takes the value 1 if all subgroup estimates are available (i.e. no r missing) and that takes the value 0 if any subgroup estimate is missing. 

pnonmissing is a dummy variable that takes the value 1 if the population share is available for all subgroups (i.e. no popshare missing) and that takes the value 0 if any population share is missing.
