### ISSUE TITLE
Tables: adjust select standard error type selections

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#117]
Change menu to "Select standard error type": Drop aggregated (also doesn't need to be calculated) and swop order of bootstrap and analytic (1. Analytic and bootstrap, 2. Analytic, 3. Bootstrap).

**Comment by zross** [comment]
@WHOequity the default selection is aggregated. What do you want as default now?

**Comment by zross** [comment]
The "Bootstrap and Analytic" is the default now. If this works can you close this issue?

**Comment by WHOequity** [comment]
Can you change the label to "Analytic and Bootstrap" and swop the columns in the table accordingly?
