### ISSUE TITLE
Content: indicator list needs updating

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#12]
List of indicators needs to be limited; indicator names need to be updated; indicators should be ordered alphabetically

**Comment by zross** [comment]
@WHOequity what do you mean by "list of indicators needs to be limited"? Will you be giving me a new list with new names?

**Comment by WHOequity** [comment]
The data accessible through HEAT should be identical to the data available online on our website (http://apps.who.int/gho/data/node.main.81?lang=en). The online version currently features 37 indicators, which is a subset of our actual database. If I share the full database with you, would it then be possible to "limit" the number of indicators that are actually accessible for the user? 

Yes, the data can (and should) be used directly to populate the pull down menus.

**Comment by WHOequity** [comment]
Please order indicators by name.
