### ISSUE TITLE
Graphs: change text in download graph button

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#122]
- Correct text in pop-up menu that appears when clicking the “Download graph” button: “Graph width (cm)” and “Graph height (cm)” (instead of “Plot width (cm)” and “Plot width (cm)”)

**Comment by zross** [comment]
@WHOequity to be consistent I also changed "Plot options"  to "Graph options". And "Select plot names" to "Select graph names". Is this what you want? What about "Select chart type", should this be "Select graph type"?

**Comment by WHOequity** [comment]
Yes please.

**Comment by WHOequity** [comment]
And please correct the text in the pop up for the download graph button: users should be able to select the height and width, not two times the width:)

**Comment by WHOequity** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13563065/10584293/b145ed68-7691-11e5-974b-9eca3bcc803f.png)

**Comment by zross** [comment]
Sorry I'm not understanding what you mean by "not two times the width" what I'm I supposed to change?

**Comment by WHOequity** [comment]
Currently, users can select 
- Graph width (cm) (default is 15) <-- should be Graph height
- Graph width (cm) (default is 12)
- Output format (default is PDF)
