### ISSUE TITLE
If time permits: graph -- dynamic y-axis labels

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#126]
This applies to both the summary and disaggregated graphs 

Possible to change the y-axis title to a flexible title: "Inequality (summary measure name)"?

**Comment by WHOequity** [comment]
Please just add the summary measure abbreviations for now, if not too time consuming.

**Comment by zross** [comment]
I put the summary measure name in for the summary plots. What do you want the disaggregated graphs to say? Right now I have "Inequality measure"

**Comment by zross** [comment]
check to see if this is done for you.
