### ISSUE TITLE
If time permits: Tables - add option to select variables to compare-disaggregated

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#131]
- Add option to add data source, national estimate and flag to table (as a separate menu in the left panel). 

Essentially, the default display for this graph should be the same as for the "Explore inequality - Disaggregated data tables", only that here, data for multiple countries and only one year, indicator and dimension is displayed (instead of for one country and multiple years, indicators and dimensions).

**Comment by WHOequity** [comment]
If possible, Disaggregated data tables under Compare inequality should be dropped. 

But, if time permits, option to select variables should be added to Summary measures tables under Explore inequality as well.
