### ISSUE TITLE
Bug: when inequal is recalculated uncomment join on source

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#132]
Original inequal data did not have source so now I'm linking without source

`ineqDF <- left_join(ineqDF, nationaldata, by=c('country', 'year', 'indic'))`

But will need to remove this when I recalculate.

**Comment by zross** [comment]
This is in get_data.R the `getInequalData` function

**Comment by WHOequity** [comment]
Does this have any implications?

**Comment by zross** [comment]
No, previously there was no "source" in the inequal database, now I need to remember that it will and adjust the code accordingly.
