### ISSUE TITLE
Formula: PAR needs standard error

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#134]
#101 I didn't realize that PAF needed it to since it's not in yellow on the spreadsheet. But I implemented it. I'm getting 2.72 and 2.44 and in the spreadhsheet I'm seeing 2.70 and 2.44.

**Comment by zross** [comment]
I'm reopening just as a reminder that we should double check results against WHO.

**Comment by WHOequity** [comment]
OK!

**Comment by zross** [comment]
Did you double check, if so, can you close this?
