### ISSUE TITLE
Formulas: which measures should be calculated

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#135]
@WHOequity can you review my table of what should be calculated when? In the Word doc the mean difference from mean has an absolute and relative entry. I'm not sure which one was implemented but they both seem to have the same rules.

![image](https://cloud.githubusercontent.com/assets/1395177/10546379/986f1fb4-73fb-11e5-9e76-b30c6fbd0899.png)

**Comment by WHOequity** [comment]
Yes, this is correct. 

Note: only the absolute version of MDM is implemented in the toolkit.
