### ISSUE TITLE
Formulas: use different SE for RR and RIIKM

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#136]
Bootstrap (boot.lowerci): exp (log(inequal) - (1.96 * boot.se/inequal) )

Bootstrap (boot.upperci): exp (log(inequal) + (1.96 * boot.se/inequal) )

Analytic (se.lowerci): exp (log(inequal) - (1.96 * se/inequal) )

Analytic (se.upperci): exp (log(inequal) + (1.96 * se/inequal) )

**Comment by zross** [comment]
@WHOequity this is done but it would be good to have you confirm when I upload the new data.

**Comment by WHOequity** [comment]
OK!
