### ISSUE TITLE
Bug: negative numbers in bootstrap

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#139]
@WHOequity as part of the bootstrap random normal data with a mean and SE similar to the input data are generated. The random normal data generation can generate negative numbers. This may or may not be an issue with most of the inequality measures but it is definitely an issue with the Theil Index because, as part of the calculation, we take a log of the values divided by the weighted mean. The log of the negative values, of course, generates an NA.

How do you want this handled? I could take an absolute value of the random normal data in which case it would be cheating a little but would probably be fine. Or perhaps you have another idea.

The negative numbers would be expected to be small -- here is the example data that caused the error:

```
[1] -0.4523927 15.1386028  1.8834095 28.9088388 27.5972510 21.4177190 11.5814215 67.0462422
 [9] 27.2054385 48.0139706 45.9009950 10.1313739 14.0712461 45.6017571 72.8529677
```

And do you know if the negative numbers would affect the other calculations? The only other one that had a log is `mld` but it looks like the boot se is disabled for this measure -- based on the notes it looks disabled for this exact reason.

**Comment by WHOequity** [comment]
I will check and get back to you tomorrow.

**Comment by WHOequity** [comment]
Let's go for the simplest solution: ignoring negative numbers (do not take the absolute value) and dropping bootstrap results for MLD and TI.

**Comment by zross** [comment]
The `MLD` did not have a bootstrap -- it was disabled with the comment:

```r
# The bootstrap for MLD is not quite right.  The process keeps looping if a negative value is generated
# because log(-ve) is NaN
```

Perhaps this was a related issue and I'll uncomment and run.

**Comment by zross** [comment]
Is it OK, that I made the numbers positive? The negative numbers are small so I don't think this a problem. Close this if it's OK.

**Comment by WHOequity** [comment]
Ok.
