### ISSUE TITLE
Bug: is there a problem in previous MLD calculations?

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#141]
@WHOequity for a small number of `mld` calculations I'm getting results that are quite far off from yours. I tracked it down to one issue.

When there is an `r` value = 0, your previous developer added `.000001` to protect against taking a log of 0. This has a big effect on the results. 

In your Stata code it looks like you set values of 0 in `r` or `pop` to missing so I assume I should do the same. Then the results match. Correct?

**Comment by WHOequity** [comment]
I will get back to you on this.

**Comment by WHOequity** [comment]
We have no special treatment of r=0 or pop=0 in our calculations. Please do the same. 

For MLD this means, removing the addition of .000001 to protect against taking a log of 0. In this case, the summary measure estimate will simply be missing (only a few cases in the dataset). 

(also answers one outstanding issue in #106 I believe).

**Comment by zross** [comment]
OK on `ti`. The `mld` boot was disabled is this needed? It says:

```r
# The bootstrap for MLD is not quite right.  The process keeps looping if a negative value is generated
# because log(-ve) is NaN
```

Perhaps this is the issue I mentioned. I will try to uncomment and run.

**Comment by WHOequity** [comment]
MLD and TI will have the same issues (both have a log in their formula). Ok to drop bootstrap for both.

**Comment by zross** [comment]
I ran this and I think it worked.
