### ISSUE TITLE
Formula: RD and RR and missing levels

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#142]
@WHOequity This also refers to: #106

Your Word doc and the note in #106 say:RR and RD are set to missing if any subgroup estimate r that is required for the calculation (only two!) is missing

For rankable dimensions I assume that the 1st and last level are the "required" subgroups. But what about for unrankable dimensions, what are the required subgroups?

**Comment by WHOequity** [comment]
The subgroups with the minimum and maximum estimates (i.e. data needs to be available for at least two subgroups). 

See also: issue #140
