### ISSUE TITLE
If time permits: add compare/summary table

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#144]
In addition, we'd also like a tab for "Summary measures (tables)" showing the summary measures for all benchmark countries in a table format. #48

**Comment by zross** [comment]
@WHOequity you added this as an issue. I agree that this is important but it was not part of the TOR and would take some time so this is a "if time permits" for me. We can discuss.

**Comment by WHOequity** [comment]
If possible, disaggregated data tables under compare inequality should be dropped. In this case, summary measures tables are not needed either.

**Comment by zross** [comment]
I dropped this
