### ISSUE TITLE
Graph: Height of graph should increase with increasing number of selected years...

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#159]

**Comment by zross** [comment]
•	Height of graph should increase with increasing number of selected years, indicators and dimensions. If this is not possible, the menus to manually select the graph height and width should be added to the sidebar panel.

**Comment by zross** [comment]
@WHOequity I'm not sure how to handle. I put the sliders back for the disaggregated/explore tab. Is this what you'd prefer? It would be too complicated probably to have the plot automatically resize height based on input.

**Comment by WHOequity** [comment]
The sliders work too. What is the scale for the sliders? The breaks seem uneven (at 200, 350, 500, 650 etc. ) - can this be adjusted?

**Comment by zross** [comment]
This is what I'm seeing in the previous app, I will add as an if time permits.
