### ISSUE TITLE
Bug: Downloaded graphs don’t show correctly.

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#161]
disag graphs

**Comment by zross** [comment]
@WHOequity can you give me an example? The plots look OK to me. I adjusted all the various heights and widths and the downloaded plots

**Comment by WHOequity** [comment]
[Indonesia_disaggregated_2015-10-28 (4).PDF](https://github.com/WHOequity/who-heat/files/22383/Indonesia_disaggregated_2015-10-28.4.PDF)

**Comment by WHOequity** [comment]
The default size (24 x 24 cm) seems to be good for all graphs (i.e. the graph and font size automatically adjust depending on how many variables are selected) . It's only when I change the width and height that the graphs don't show correctly anymore (e.g. 15 x 10 cm for examples below).

**Comment by WHOequity** [comment]
[Indonesia_disaggregated_2015-10-28 (8).PDF](https://github.com/WHOequity/who-heat/files/22386/Indonesia_disaggregated_2015-10-28.7.PDF)

[Indonesia_disaggregated_2015-10-28 (7).PDF](https://github.com/WHOequity/who-heat/files/22387/Indonesia_disaggregated_2015-10-28.7.PDF)

**Comment by zross** [comment]
This is actually not really a bug, it is working as intended. It takes the users' original plot (and its height and weight) and simply changes the dimensions without scaling. We can add a scale factor but this would take me some time to get right. Since the user can adjust the plot dimensions on the app now should I drop the ability to change size in the pop-ups?

**Comment by WHOequity** [comment]
Let's leave it as it is now. We'll see what comments the reviewers have.

**Comment by zross** [comment]
I actually already edited the ability to change size in the pop-ups out. I agreed that it would cause issues. OK if we leave this edited out for now or do you want me to restore?

**Comment by WHOequity** [comment]
Ok that's fine too.
