### ISSUE TITLE
Bug: make benchmark options adjust

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#168]
•	The benchmark options do not adjust according to the selected main country of interest (the selection always remains to be Middle-income countries from the South-East Asia region, regardless of the selected main country of interest).

**Comment by zross** [comment]
I think I've got this done. I did not realize that you wanted them to change with every new change -- I thought you were just setting the initial settings. If you're happy close this. You'll note that there are instances where there is just one country is a region/income category. so it can't select anything to benchmark against. See Trinidad Tobago.

**Comment by WHOequity** [comment]
If the selected country is the only country from that region/income category, please change the default to no benchmark countries selected (instead of all countries selected). Otherwise this is working well now.

**Comment by zross** [comment]
Believe it or not, this is actually a little time consuming. All the other parts of the app have the rule that if the text box is empty treat it as if ALL are selected. So we don't have a "no selection" option actually.
