### ISSUE TITLE
Bug: country codes and bullets turn into letter "a"

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#169]
•	When country codes are selected to show in graph, then bullet points in legend turn into the letter “a”.

**Comment by zross** [comment]
@WHOequity I will do something different but this is not a bug, when we're displaying text, the legend has text. What do you want instead?

**Comment by zross** [comment]
I put a set of colored lines. If the text is color-coded it seems the colors should be defined somehow (unlike the previous app).

**Comment by WHOequity** [comment]
Much better!
