### ISSUE TITLE
Design: see table in word doc just sent

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#172]
![image](https://cloud.githubusercontent.com/assets/1395177/10670887/be3fc112-78b5-11e5-9ed4-e0e865576d38.png)

**Comment by WHOequity** [comment]
Do you have any questions on this?

**Comment by WHOequity** [comment]
Please make the following changes to the text in the left panel menu:
- change text: 
  - "Variable options" to "Explore inequality" in all explore tabs
  - "Variable options" to "Compare inequality" in all compare tabs
- if possible, remove the space between the most recent year check box and the year dropdown menu
- change text and make not bold in explore-disaggregated and explore-summary graphs: 
  - "Axis-min" to "Axis minimum"
  - "Axis-max" to "Axis maximum 
- change text and make not bold in compare-disaggregated graphs: 
  - "X-axis min" to "Axis minimum"
  - "X-axis max" to "Axis maximum"
- change text and make not bold in compare-summary graphs: 
  - "X-axis min" to "Horizontal axis minimum"
  - "X-axis max" to "Horizontal axis maximum"
  - "Y-axis min" to "Vertical axis minimum"
  - "Y-axis max" to "Vertical axis maximum"
- add space above subtitle "Select axis range" in all graphs
- change text and/or make not bold in all graphs: 
  - "Main title" (leave as is)
  - "X-axis label" to "Horizontal axis title"
  - "Y-axis label" to "Vertical axis title"

**Comment by zross** [comment]
Close if you agree that this is complete. This took longer than expected because name changes and font-weight changes caused alignment issues.

**Comment by WHOequity** [comment]
I don't think this is showing up yet in the online application?

**Comment by WHOequity** [comment]
Seeing it now. Looks great! A few more comments: 
- In explore-summary tables: 
  - can you please move "Select estimate precision" below "Select table content"?
  - can you please add a white line and the subtitle "Table options" above the two items (similar to what we have in explore-disaggregated tables)?
- In explore-summary graphs and compare-summary graphs: 
  - can you please also change the texts for "Horizontal axis title" and "Vertical axis title" (same as what we have in explore-disaggregated graphs and compare-disaggregated graphs)?
- Can you please change the title to plural in explore-summary tables: "Select summary measures" (currently still singular)
- Can you please change the titles to singular in compare-disaggregated and compare-summary tables: "Select year", "Select health indicator" and "Select inequality dimension" (currently still plural)
