### ISSUE TITLE
Graph clarification: "fix width of bars"

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#176]
@WHOequity On summary measures bar chart you have "fix width of bars"  what does this mean?

**Comment by WHOequity** [comment]
"Fix width of bars" applies to both disaggregated data bar chart and summary measures bar chart. 

Currently, if only one year, indicator and dimension is selected, the bars are very wide (less so in the disaggregated data graph, but in the summary measures graph only one big bar appears), whereas if many variables are selected the bars become very narrow. Both extremes look a bit bizarre and make it difficult to read the graph (see screenshots below for a few examples). 

It would be good to have a maximum and minimum width that the bars can take, regardless of how many variables are selected to ensure readability. Is this possible?

**Comment by WHOequity** [comment]
![untitled11](https://cloud.githubusercontent.com/assets/13563065/10688839/7e017074-7977-11e5-9621-812000553d36.png)
![untitled11](https://cloud.githubusercontent.com/assets/13563065/10688844/8496a206-7977-11e5-9eca-0ccdf0471257.png)
![untitled](https://cloud.githubusercontent.com/assets/13563065/10688845/8823f7ac-7977-11e5-9c86-67ec923cd6c4.png)
![untitled22](https://cloud.githubusercontent.com/assets/13563065/10688846/8b493348-7977-11e5-909e-7a01f4e4f33e.png)

**Comment by zross** [comment]
Without a large amount of time this will always be a bit of an issue since we will generally have different width bars etc. What I did was that if the number of bars is 1 or 2 I changed the width to less wide. I also added two "phantom" years on either side of the bar (or point estimate) if there is just one year of data to make it less ugly. Please close if this works (at least for now).
