### ISSUE TITLE
Bug: Is there a problem with Indonesia region names?

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#177]
In the raw data file you sent I'm seeing regions with different spelling and capitalization. Are these correct? Should they be different?

02 North Sumatera
02 north sumatra
01 north sumatra

02 west sumatra
03 West Sumatera
03 west sumatra

**Comment by WHOequity** [comment]
Yes, it's true that the same subnational regions may have different names or that the names may be spelled differently in different survey years (true for many countries, not just Indonesia). This is how the names for subnational regions were recorded by Demographic and Health Surveys (DHS) and Multiple Indicator Cluster Surveys (MICS) and we did not touch these. Only the two digit code was added to facilitate readability and to retain the original order (if that has any meaning). It's not ideal, but please leave as it is.
