### ISSUE TITLE
If time permits:Add button to hide/show error bars.

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#180]

**Comment by zross** [comment]
This is implemented please close if you agree.

**Comment by WHOequity** [comment]
Agreed. Can we move the button between "Select graph type" and "Select graph height"? And can we make the text black?

**Comment by WHOequity** [comment]
I can't see the lower end of the error bars in the barchart because they have the same colour as the bar. Is it also possible to either add some transparency to the bars or to have the error bars in a different colour?

**Comment by WHOequity** [comment]
Which type of error bars are currently displayed (analytic or bootstrap)?

**Comment by zross** [comment]
these are analytic. I made them grey. Please close if OK.

**Comment by WHOequity** [comment]
Ok for now. It'd be great if users could choose between the type of error bars displayed.
