### ISSUE TITLE
Graph: add full name of indicators in titles etc if possible.

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#185]

**Comment by zross** [comment]
This is implemented for all but the scatter plot. Please close if you agree.

**Comment by WHOequity** [comment]
The box and the text for this option don't seem to be completely inline. Not sure why this is (as it seems to be working well for the option to add 95%CIs to the graphs). Can this be fixed?

**Comment by zross** [comment]
This is fixed. If you agree please close this.
