### ISSUE TITLE
Graph: if only one year on bar or line perhaps add blank years

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#186]
In the dot plots and bar plots when we have just one year the error bars and bars are too wide. This might be an approach.

**Comment by zross** [comment]
example is summary graphs with one year. This has been implemented.

**Comment by zross** [comment]
@WHOequity if OK please close

**Comment by WHOequity** [comment]
Looks great for summary measure data! It's not necessary for disaggregated data. Here the bars quickly become too thin, even if only one year but subnational region data is selected. I'm not sure, though, if this is implemented for disaggregated graphs as well?
