### ISSUE TITLE
If time permits: legends, one row or column per dimension

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#187]
In the disaggregated data graphs, the legends list the colour for each subgroup. Can we group legend colours/subgroups by dimension? Either one row or one column for each dimension?

**Comment by zross** [comment]
Yes, I have not re-instituted the legends yet.

**Comment by zross** [comment]
I put the legends approx back the way they were in the original app -- for 1 row per dimension this would take extra time.

**Comment by WHOequity** [comment]
Ok,
