### ISSUE TITLE
If time permits: Close second Firefox window for standalone version

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#192]
When you click on the batch file (Start_Toolkit.bat), two Portable Firefox windows open: one window displaying the toolkit and one empty window. Is it possible to keep the empty window from opening up?

**Comment by zross** [comment]
probably, but this is what happens in the original app, so I'm adding to time permits

**Comment by zross** [comment]
This should be fixed. I added a new bat and R file for starting the toolkit to a new folder called "portable_related" under who-heat. Copy and replace those and give it a test. Please close if agreed:

https://github.com/WHOequity/who-heat/tree/master/portable_related

**Comment by WHOequity** [comment]
Yes, this is working well.
