### ISSUE TITLE
Downloadable data tables

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#194]
If possible, please rename and reorder variables in downloadable data tables as listed in the document below.

**Comment by WHOequity** [comment]
[HEAT Comments - 2015-10-26.docx](https://github.com/WHOequity/who-heat/files/22364/HEAT.Comments.-.2015-10-26.docx)

**Comment by WHOequity** [comment]
If possible, please also change the default display for estimates to one decimal.

**Comment by zross** [comment]
How do you want to handle the new "full name" summary measure? Is this downloadable?

**Comment by WHOequity** [comment]
Good point! Yes, it'd be good to add that to the downloadable tables as well. The two variable names should then be: "measure_abbr" and "measure_name"

**Comment by zross** [comment]
done, please close if agreed

**Comment by WHOequity** [comment]
Agreed. 

Can you please also drop the variable "population_size" from the downloadable data tables for disaggregated data (Explore-disaggregated tables, Explore-disaggregated graphs, and Compare-disaggregated graphs). It's not really needed. Only the population share is relevant for the correct interpretation of the data.

**Comment by WHOequity** [comment]
Also see #226

**Comment by zross** [comment]
This is done, please close if agreed.
