### ISSUE TITLE
Link to Health Equity Monitor database in Home

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#195]
When I click on the link to the "Health Equity Monitor database" in the text on the welcome page, the app goes grey and the link doesn't open. It does however open in a new tab, when I right click and select to open the link in a new tab. Can we make this the default (i.e. when you click on the link it should open in a new tab)?

**Comment by zross** [comment]
Close if you agree this is OK.

**Comment by WHOequity** [comment]
It's still not working for me. I'm using google chrome.

**Comment by zross** [comment]
Sorry, didn't know you were still in the office, I have not posted the change. Very soon
