### ISSUE TITLE
Select table content menu

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#198]
When adding variables to the explore-disaggregated tables and explore-summary tables, those variables are added at the end of the table. Is it possible to retain a similar order as in the downloadable data tables: 

- explore-disaggregated tables: 
  - country
  - year
  - source
  - indicator_abbr
  - indicator_name
  - dimension
  - subgroup
  - estimate
  - 95ci_lb
  - 95ci_ub
  - population_share
  - flag
  - national

- explore-summary tables: 
  - country
  - year
  - source
  - indicator_abbr
  - indicator_name
  - dimension
  - measure_abbr
  - measure_name
  - estimate
  - analytic_95ci_lb
  - analytic_95ci_ub
  - bootstrap_95ci_lb
  - bootstrap_95ci_ub
  - national

**Comment by zross** [comment]
I've updated (uploading now)
