### ISSUE TITLE
If time permits: Log scale for RR (and RIIKM) in graphs

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#199]
To be methodologically correct, the range ratio (and the kunst mackenbach relative index of inequality, but we dropped this one from HEAT) should be displayed on a log-scale in graphs, so that the reference value is 1 (and not 0, as is the case for all other summary measures). Can this be implemented? 

For explore-summary graphs (line graphs and bar graphs), the y-axis would need to change to a log-scale. In addition, the bar graphs would need to start at 1 (not 0). 

For compare-summary graphs (scatterplot), the y-axis would need to be changed to a log-scale.

**Comment by zross** [comment]
Changed this to if time permits. It could be done but would take some time.

**Comment by WHOequity** [comment]
Ok.

**Comment by zross** [comment]
Take a look and see what you think. I assumed you wanted the scale on the y axis to be log rather than taking the log of the values. Is this what you had in mind?

**Comment by WHOequity** [comment]
Yes, correct. Looking good!
