### ISSUE TITLE
If time permits: 95% confidence intervals in bar graphs

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#200]
It would be great if we could 
- add 95% confidence intervals to the explore-disaggregated bar graph (same as what we have for the explore-summary bar graph) and 
- add the numbers for summary measure estimates on top of the bars for explore-summary bar graphs (same as what we have in the explore-disaggregated bar graphs)

The default display should then be the numbers on top of the bars. If users tick the check box in the sidepanel to "Include 95% confidence intervals" (would need to be added to the explore-disaggregated bar graph), then the numbers disappear and the 95% confidence intervals appear.

**Comment by zross** [comment]
I changed this to "if time permits" OK?

**Comment by WHOequity** [comment]
Yes!

**Comment by zross** [comment]
Added CI to explore disag bar graphs
Added numbers to top of bars for explore summary
