### ISSUE TITLE
Bug: Error message for variable combinations with missing data for all subgroups

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#201]
When a variable combination is selected, where data is missing for all subgroups (e.g. Afghanistan, 2010, dtp3, economic status), 
- an empty table appears in explore-disaggregated tables
- error message appears in explore-disaggregated graphs and compare-disaggregated graphs
- all summary measure tabs report that "There is no data for this combination of variables"

On the contrary, when a variable combination is selected that is not available in the dataset (e.g. Cuba, 2010, dtp3, economic status)
- all explore tabs report that "There is no data for this combination of variables"
- the compare-disaggregated graph only shows available data for benchmark countries
- the compare-summary graph reports that "There is no data for this combination of variables"

From our point of view, both cases should be treated the same: all tabs should report that "There is no data for this combination of variables"

**Comment by WHOequity** [comment]
#93

**Comment by zross** [comment]
This should be solved (uploading now). I'm not certain, though, what will happen and what you want to happen if the user selects multiple indicators or dimensions etc and one of them is all missing. Perhaps you have an example of this.

**Comment by WHOequity** [comment]
Yes, this is for example the case for Cuba, 2010, dtp3. Here data for economic status is not in the dataset (i.e. missing), data for education is in the dataset, but is missing for all education subgroups and data is available for place of residence, sex and subnational region. 

When only education is selected, then 
- all explore inequality tables and graphs report that "There is no data for this combination of variables", which is correct
- the compare-disaggregated graphs are shown with data for Cuba missing, which is incorrect (the warning message "There is no data for this combination of variables" should appear)
- the compare-summary graphs report that "There is no data for this combination of variables", which is correct

When education and e.g. place of residence are selected, then 
- explore-disaggregated tables: education subgroups are displayed in the table with all rows missing, which is incorrect (they should be missing)
- explore-disaggregated graphs: 
  - the empty line graph for education is shown, which is incorrect (only the line graph for place of residence should appear)
  - an error message appears when the bar graph is selected ('x' and 'units' must have length > 0), which is incorrect (only the bar graph for place of residence should appear)
- explore-summary tables: summary measures for education are missing in the table, which is correct
- explore-summary graphs: no line or bar graph is shown, which is correct

**Comment by WHOequity** [comment]
I'm thinking it may be easier to update our dataset and to drop all cases, where data is missing for all subgroups. 

So, for example, data for Cuba, 2010, dtpv, education would be dropped from the database and would then be treated the same as data for Cuba, 2010, dtpv, economic status (which is not available in the database). Here, the above listed issues don't occur. 

What do you think?

**Comment by zross** [comment]
Yes, I think dropping them makes sense. An easy fix, though, would be for me to make a small change to the calculate_raw_tables.R table. The pulldown menus depend on the strata.RDS file which is all possible combinations of country, indicator etc. So I can change the part where I create strata.RDS to exclude strata with no data. Then they would not be displayed. Let me know.

**Comment by WHOequity** [comment]
Yes, that sounds like a good approach. Please exclude strata with no data. I will add some further comments on observed bugs/handling of missing data in a new issue.
