### ISSUE TITLE
Change column names in tables

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#206]
Can you please change the following column names in
- explore-disaggregated table: 
  - “Lower 95%CI” to “95%CI lower bound"
  - "Upper 95%CI” to “95%CI upper bound”
- explore-summary table: 
  - “Analytic Lower 95%CI” to “Analytic 95%CI lower bound”
  - “Analytic Lower 95%CI” to “Analytic 95%CI lower bound”
  - “Bootstrap Lower 95%CI” to “Bootstrap 95%CI lower bound”
  - “Bootstrap Lower 95%CI” to “Bootstrap 95%CI lower bound”

**Comment by zross** [comment]
done, close if agreed
