### ISSUE TITLE
Bug: 95%CIs in explore-summary bar graphs do not go below zero

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#207]
The 95%CIs for summary measure estimates don't seem to go below zero in bar graphs, even if the value for the lower bound is smaller than zero. 

Example: Honduras, DHS 2011, Measles, Economic status, Range Difference.

**Comment by zross** [comment]
I assumed that with a bar graph we shouldn't display values below zero, but if this is what you want, I have updated. See if it works (and close if it does).

**Comment by WHOequity** [comment]
The bar graphs for disaggregated data only display positive numbers, correct. The bar graphs for summary measures can display negative numbers, if estimates or corresponding 95%CIs are negative. Looks good!
