### ISSUE TITLE
Handling of disaggregated data estimates that are equal to zero

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#211]
Disaggregated data estimates that are equal to zero should be displayed correctly in disaggregated data tables and relevant summary measures should be calculated and displayed correctly.

**Comment by WHOequity** [comment]
RE: disaggregated data tables
- In some cases, estimates that are equal to zero are shown correctly in the Explore Inequality – Disaggregated data tables
  - Example: Armenia, DHS 2005, uweight3 by subnational region
  - Example: Armenia, DHS 2005, uweight5 by subnational region
  - Example: Armenia, DHS 2005, wast3 by subnational region
  - Example: Armenia, DHS 2010, uweight3 by subnational region
  - Example: Armenia, DHS 2010, wast3 by subnational region
- While in other cases, estimates that are equal to zero are shown as missing in the Explore Inequality – Disaggregated data tables (which is incorrect)
  - Example: Armenia, DHS 2000, wast3 by subnational region
  - Example: Armenia, DHS 2000, wast5 by subnational region
Please correct this.

**Comment by WHOequity** [comment]
RE: summary measures

Regardless of whether estimates are displayed correctly or not, there are inconsistencies in the calculation of MLD and TI (for subnational region): TI is always calculated, while MLD is never calculated if one of the subgroup estimates is equal to zero. This cannot be right, as the calculation of both measures involves taking the log of zero. Please correct this.

**Comment by zross** [comment]
Are you using the portable or online? I'm not seeing your examples missing:

![image](https://cloud.githubusercontent.com/assets/1395177/11063651/28128550-8786-11e5-8aeb-98bc77890aa6.png)

**Comment by WHOequity** [comment]
I was looking at this yesterday, but can't find it now. Seems to be ok then. Will let you know if I come across it again.
