### ISSUE TITLE
Handling of missing data: adding disclaimers to tables and graphs

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#212]
Please add the following disclaimers
- above the table in Explore Inequality – Disaggregated data tables and above the graph in Explore Inequality – Disaggregated data graphs: "If estimates are not shown for a selected combination of variables, then data are not available." 
- above the table in Explore Inequality – Summary measures tables and above the graph in Explore Inequality – Summary measures graphs: "If summary measures are not shown for a selected combination of variables, then data are not available or summary measures cannot be calculated. Note that only relevant summary measure are calculated for each dimension."

These disclaimers should always be shown when tables and graphs are shown. 

Only if the selected country-year-indicator-dimension combination(s) is not available (i.e. data are missing for all subgroups and no tables or graphs are shown), the warning message "There is no data for this combination of variables." should be displayed instead.

**Comment by zross** [comment]
This was quite a bit more challenging than expected but should be implemented. I don't believe any new bugs were added but on this one but I needed to rewrite some code.

For my own reference: the `renderDataTable`s and `renderPlot`s needed to be converted to `renderUI` to add the warning wrapped on top.

**Comment by WHOequity** [comment]
Looks great! For situations where data is missing for some subgroups (issue #227), the disclaimers should also be added to the Compare Inequality tabs, please.

**Comment by zross** [comment]
This has been added.

**Comment by WHOequity** [comment]
Can you please change the disclaimer for the Compare Inequality - Summary measures graphs tab to: "If estimates are not shown for a selected combination of variables, then data are not available or summary measures cannot be calculated. Note that only relevant summary measures are calculated for each dimension."

I also noticed a (my) typo in the disclaimer for the Explore Inequality Summary measures tables and graphs. Can you please change "Note that only relevant summary measure..." to "...summary measures..." (i.e. plural!)?
