### ISSUE TITLE
Handling of missing data: missing data for all subgroups

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#213]
If disaggregated data are missing for all subgroups of a selected country-year-indicator-dimension combination, this should always be handled as follows:
- Case 1: If ONLY the country-year-indicator-dimension combination with missing data for all subgroups is selected, then all Explore Inequality and Compare Inequality tabs should display the warning message “There is no data for this combination of variables.” (i.e. no tables or graphs displayed in any tab). 
- Case 2: If the country-year-indicator-dimension combination with missing data for all subgroups AND another country-year-indicator-dimension combination with available data (for some or all subgroups) are selected, then all Explore Inequality tabs should only display the country-year-indicator-dimension combination with available data (not applicable for Compare Inequality tabs as only one indicator and dimension can be selected at a time)

Overview: 
![handling of missing data - missing data for all subgroups 2015-11-10](https://cloud.githubusercontent.com/assets/13563065/11063618/41a0bb36-87b8-11e5-829e-76dfe95047d6.png)

**Comment by WHOequity** [comment]
Examples where this is not correctly implemented: 
- ONLY the country-year-indicator-dimension combination with missing data for all subgroups is selected: Afghanistan, MICS 2010, cci by economic status
  - The Explore Inequality – Summary measures tables display missing summary measure estimates (which is incorrect). 
  - The Explore Inequality – Summary measures graphs give the error message “Error: ‘from’ must be of length XX” (which is incorrect). 
  - The Compare Inequality – Disaggregated data graphs display the line chart with missing data for the main country of interest (which is incorrect). 
  - The Compare Inequality – Summary measures graphs display the scatterplot with missing data for the main country of interest (which is incorrect). 

- The country-year-indicator-dimension combination with missing data for all subgroups AND another country-year-indicator-dimension combination with available data (for some or all subgroups) are selected: Afghanistan, MICS 2010, cci and anc1 by economic status
  - The Explore Inequality – Disaggregated data tables display data for all variable combinations, including those with missing data for all subgroups (which is incorrect). 
  - The Explore Inequality – Disaggregated data graphs (line graph) display two graphs, one for each indicator-dimension combination (which is incorrect). 
  - The Explore Inequality – Disaggregated data graphs (bar graph) gives the error message: Error: ‘from’ must be of length XX” (which is incorrect).
  - The Explore Inequality – Summary measures tables display summary measure estimates for all variable combinations, including those with missing disaggregated data for all subgroups (which is incorrect).

**Comment by zross** [comment]
I believe that some of this will be solved "automatically" when we implement #201. I will adjust the code for the calculation of the strata such that only strata with non-missing data will be included. Then the inequal value (missing values) will not show up and get the warning. I'll see.

**Comment by WHOequity** [comment]
Ok. But only strata with missing data for all subgroups should be dropped. Strata with missing data for some subgroups should be included. I will add a separate issue on how they should be displayed.

**Comment by zross** [comment]
This is not yet done, FYI, still working on it. For my own reference: strata with completely missing data are removed so maindata, nationaldata and inequals might need to be `inner_joined`

**Comment by zross** [comment]
Can you take a look and see how this is behaving. I think I have this done.

**Comment by WHOequity** [comment]
Yes, looks good! 

FYI I think the Explore Inequality tables (both disaggregated and summary) are doing a double calculation when you add an indicator or dimension with available data. For example, when looking at the disaggregated data table for Afghanistan, DHS 2010, cci by economic status, the warning message "There is no data for this combination of variables". When adding the indicator anc1, the table flashes once before the correct data is displayed.
