### ISSUE TITLE
Bug: 95% confidence intervals for RCI, MLD and TI

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#215]
Relative concentration index: 
Analytic and bootstrapped 95% confidence intervals (lower and upper bounds) need to be divided by 100 (they are automatically multiplied by 100 if the relevant check box is ticked in the Explore inequality – Summary measures tables tab).

Mean log deviation: 
Bootstrapped 95% confidence intervals (lower and upper bounds) need to be divided by 1000 (they are automatically multiplied by 1000 if the relevant check box is ticked in the Explore inequality – Summary measures tables tab).

Theil index: 
Bootstrapped 95% confidence intervals (lower and upper bounds) need to be divided by 1000 (they are automatically multiplied by 1000 if the relevant check box is ticked in the Explore inequality – Summary measures tables tab).

**Comment by zross** [comment]
I had multiplied by 100 or 1000 in the inequal calculation procedure in order to match the table that was provided. I have removed this multiplication (which means the values will not match exactly those in the XLS file provided to me). The table will need to be recalculated.

**Comment by zross** [comment]
OK, I think I have this right. Please take a look. If it's fine close. If not please give me a specific example with what the values should be.
