### ISSUE TITLE
Feedback round 1: make long health indicator and summary measure names default

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#220]
Please make long health indicator names and long summary measure names the default in all tables and graphs, i.e. 
- tables display long health indicator names and long summary measure names instead of abbreviations and users have the option to add the abbreviation to the table
- graphs display long health indicator names (with the check box for long health indicator names ticked)

**Comment by zross** [comment]
Check to see if this is done, please upload.

**Comment by zross** [comment]
Check to see if this is done.
