### ISSUE TITLE
Feedback round 1: default main titles for graphs

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#225]
It would be good to populate the main titles for graphs with default settings (country etc.), which the user can then amend (since we are already giving users the ability to add those titles). Suggested default titles: 
- Explore inequality - Disaggregated data graphs: "[country], [source] [year]"
- Explore inequality - Summary measures graphs: "[measure_name] in [country], [source] [year]"
- Compare inequality - Disaggregated data graphs: "[indic_name] by [dimension] in [no. of countries] countries"
- Compare inequality - Summary measures graph: "[indic_name]: national average and within-country inequality (according to [dimension]) in [no. of countries] countries"

**Comment by zross** [comment]
These are pretty busy. Also the full indicator name gets repeated, but I've implemented this.
