### ISSUE TITLE
Bug: calculation of RD and RR for subnational region

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#228]
In case of "subnational region", RD and RR should only be calculated if data are available for all subgroups (same rule as for PAR and PAF). Otherwise, RD and RR should be missing. 

Contrary examples (where data is missing, but RD and RR are calculated): 
- Albania, DHS 2008, ort by subnational region
- Burkina Faso, DHS 2010, carep by subnational region

**Comment by zross** [comment]
This is done, but I will wait to hear other changes before re-calculating the table:

Used same code from PAR and PAF

```r
    if(!rankable & any(is.na(x))) { 
      return(list(inequal.rd=NA, se.rd.boot=NA, se.rd.formula=NA))
    }
```
