### ISSUE TITLE
Plots: National average should always start on new line

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#240]
![image](https://cloud.githubusercontent.com/assets/1395177/11325599/f1030c8a-911f-11e5-9ef3-b3c3d3edec90.png)

**Comment by WHOequity** [comment]
This actually looks a bit funny in some cases (see screenshot below). We discussed and decided to leave it as it was before (i.e. no line break). Can you please reverse this? 

![untitled](https://cloud.githubusercontent.com/assets/13563065/11335578/a601f552-91dd-11e5-88ee-121a6e875206.png)

**Comment by WHOequity** [comment]
A different title appears now (same as in Compare Inequality - Disaggregated data graphs): 

![untitled](https://cloud.githubusercontent.com/assets/13563065/11340957/ac942566-9200-11e5-9217-b1e46e0b57bc.png)
