### ISSUE TITLE
Remove x-axis label in Explore Inequality - disaggregated data graphs

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#243]
Please remove the x-axis label "Year" in both line graph and bar graph. The label is actually incorrect for the line graph (see screenshot below), but we don't really need it. So please just remove for both graph types. 

![untitled](https://cloud.githubusercontent.com/assets/13563065/11335805/087edffe-91e0-11e5-89dd-de485e7e8802.png)

**Comment by zross** [comment]
Done, see if you agree.

**Comment by WHOequity** [comment]
Agreed.
