### ISSUE TITLE
Add default graph title text to "Main title" text input box

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#244]
Is it possible to add the default graph title text to the "main title" text input boxes? 

Currently, the "Main title" boxes are empty and as soon as you insert some text, the default title disappears (which is ok). However, if the user only wants to make a small change to the default title, it would be convenient if the text already appeared in the boxes, which can then easily be modified.

**Comment by zross** [comment]
Done, see if you like it.

**Comment by WHOequity** [comment]
Perfect!

**Comment by zross** [comment]
There is an odd interplay between the textbox and title that needs to get fixed.

**Comment by zross** [comment]
This has been fixed with some real effort:

Added global variables for each title, added observer for if user changes title and updates the global variable, creation of the title on change of a pull down done within the renderUI.

**Comment by zross** [comment]
See if you agree this is done
