### ISSUE TITLE
If time permits: Add tab for "Indicator compendium" under "About"

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#249]
Please add an extra tab between the "Technical notes" tab and the "Software" tab under "About". The tab should be called "Indicator compendium" and should contain a link to the Health Equity Monitor compendium of indicator definitions (http://www.who.int/gho/health_equity/outcomes/health_equity_compendium.pdf?ua=1).

**Comment by zross** [comment]
This has been implemented
