### ISSUE TITLE
If time permits: Change summary measure names for RD and RR

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#250]
How time consuming would it be to change the summary measure names for RD and RR
- from Range Difference to Difference, and
- from Range Ratio to Ratio?

**Comment by zross** [comment]
Can I leave the abbreviations as is? ("rd", "rr"). Changing the longer names is quick but it would take time to change the abbreviation since this is what I use as the "ID" in the tables. I wouldn't take a ton of time but 30 minutes probably.

**Comment by WHOequity** [comment]
No, please change the abbreviations to "d" (for difference) and "r" (for ratio). Also the names in the dropdown menus should appear as "Difference (D)" and "Ratio (R)".

**Comment by zross** [comment]
This should be done. Note that I changed the existing table of inequal values rather than re-computing for now because recompute takes a few hours.
