### ISSUE TITLE
Bug: Most recent year not correctly applied in Compare inequality - Summary measures (graphs)

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#251]
Example: 
- Country of interest: Colombia
- Data source: All
- Year: Alternating between "2010" and "Most recent year"
- Indicator: Antenatal care - at least one visit (in the two or three years preceding the survey)
- Dimension of inequality: Economic status
- Benchmark countries: Middle-income countries from the Americas
- Benchmark years: 2 years
- Summary measure: Range difference

The Compare Inequality - Disaggregated data tab handles the issue correctly: regardless of whether "2010" or "Most recent year" is selected, data is displayed for 8 countries (see two screenshots below). 

![example1](https://cloud.githubusercontent.com/assets/13563065/11877149/bf03c8fa-a4ed-11e5-89ac-30637c8b3dcc.png)

![example2](https://cloud.githubusercontent.com/assets/13563065/11877153/c2c3805c-a4ed-11e5-8046-ef2d587d3527.png)

However, in the Compare Inequality - Summary measures tab, the two situations seem to be handled differently. When "2010" is selected, data are displayed for 8 countries, whereas if "Most recent year" is selected, data are displayed for only 7 years (Bolivia is missing). 

![example3](https://cloud.githubusercontent.com/assets/13563065/11877174/ed3711fa-a4ed-11e5-8d5d-bf1903f881d2.png)

![example4](https://cloud.githubusercontent.com/assets/13563065/11877175/f070a3cc-a4ed-11e5-8fb1-a8fc81c70b11.png)

Do you have an idea why this is? I remember we had a similar issue in the Compare Inequality - Disaggregated data tab before, but this was obviously fixed...

**Comment by zross** [comment]
Thanks for noticing this, it should be fixed. The app grabs the "anchor" country and the benchmark countries separately and was not dealing with the correct years in all cases for benchmark countries as a result. I added an argument allowing for an "anchorCountry" in the get data function to be used to grab most recent year.
