### ISSUE TITLE
If time permits: Change default view for Explore inequality tables

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#254]
Please remove the 95% confidence intervals from the default table view for disaggregated data and summary measures (workshop participants felt that this made the tables too busy).

**Comment by zross** [comment]
See my comment for #253 I'm not understanding how the CI is related to disaggregated data.

**Comment by zross** [comment]
This is done.

**Comment by WHOequity** [comment]
I can still see the 95% confidence intervals in tables. Can you double-check?

**Comment by zross** [comment]
Sorry, I missed that you wanted this changed on the tables as well as plots. This is now done.
