### ISSUE TITLE
If time permits: separate database from toolkit

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#256]
If possible, please separate the database from the toolkit. Ideally, it should be saved in a separate database folder alongside the other main folders (FirefoxPortable, R-Portable and shiny).

**Comment by zross** [comment]
I re-named the data folder to who-data and moved it two directories up. In the GitHub version this puts the who-data directory at the same level as the who-heat folder. This means that GitHub will not see this folder (outside the git scope) and it will not be added to the Git repository. 

In the app itself, I changed all references in the `initial_settings.R` from "data/blah.RDS" to "../../who-data/blah.RDS". I am assuming this will work fine in the portable, it will require manually creating a who-data folder and putting it two directories up from where it is now -- so the who-data folder will be next to shiny, R-Portable etc.

Once other changes are made we can test this.

![image](https://cloud.githubusercontent.com/assets/1395177/12175492/9b1a48b2-b530-11e5-8c0b-6b53a41dfc75.png)

**Comment by WHOequity** [comment]
Sounds good!
