### ISSUE TITLE
Bug: remove variable leads to issues

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#259]
Ahmad is reporting that even removing one variable from the summary table is getting an error pop-up.

**Comment by yihui** [comment]
I think I finally figured out this issue on my plane back home today. Will push a fix later.

**Comment by zross** [comment]
That would be great!

**Comment by yihui** [comment]
This should be the same issue as #229. I just pushed a fix to shiny (not merged yet): https://github.com/rstudio/shiny/pull/1096 The same problem has been fixed in DT, though (I know you are not using DT yet, but in the long run, I'd recommend you to switch to DT).

**Comment by zross** [comment]
I did the conversion to DT for the two tables just now -- the app at [this location](https://spatial.shinyapps.io/WHO_HETK/). The issue (of course) is still there and is actually "worse" in the sense that the alert comes up even on table load. As far as a fix in my particular instance any guess on an ETA @yihui? Will I have to update to a development version of shiny to do the fix? I'm worried about other consequences if I upgrade this particular app.

cc @WHOequity

**Comment by yihui** [comment]
If you were to switch to DT, you have to convert all tables in the app using DT. It is unlikely to work if you mix up DT::renderDataTable and shiny::renderDataTable.

Before the shiny PR is merged, you can test it with

```r
devtools::install_github('yihui/shiny@bugfix/datatables-warning')
```

(again, use either pure shiny DataTables or pure DT)

**Comment by zross** [comment]
Yikes! Is there more I need to know about the new version of shiny. When I installed the dev version my home page loads but the "explore inequality" -- where the table is -- does not load at all and gives no warning. I'm unable to see if the table bug is fixed.

When I go back and reinstall the non-development version the "explore inequality" set of tabs works.

Note that it looks like you edited your comment above, I had initially run the development version of the bugfix. This didn't seem to fix the bug, but the table did show up.

What is different that would make the page with the table not load at all with no warning?

**Comment by zross** [comment]
It seems to be related to shinyBS. When I turn off all the modals and collapses, then things seem to be loading.

**Comment by yihui** [comment]
Yes, I edited the comment since the PR has been merged. It works well for me: https://youtu.be/JL6ioXL4AYU Here is my session info, and it could be the problem of shinyBS.

```r
> devtools::session_info()
Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, darwin15.2.0        
 ui       RStudio (0.99.1050)         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Chicago             
 date     2016-02-04                  

Packages -----------------------------------------------------------------------
 package      * version     date       source                            
 assertthat     0.1         2013-12-06 CRAN (R 3.2.1)                    
 colorspace     1.2-6       2015-03-11 CRAN (R 3.2.1)                    
 DBI            0.3.1       2014-09-24 CRAN (R 3.2.1)                    
 devtools       1.10.0      2016-01-23 CRAN (R 3.2.3)                    
 digest         0.6.9       2016-01-08 CRAN (R 3.2.3)                    
 dplyr        * 0.4.3       2015-09-01 CRAN (R 3.2.2)                    
 ggplot2      * 2.0.0       2015-12-18 CRAN (R 3.2.3)                    
 gtable         0.1.2       2012-12-05 CRAN (R 3.2.1)                    
 htmltools      0.3.1       2016-01-07 Github (rstudio/htmltools@7b95c2d)
 httpuv         1.3.3       2015-08-04 CRAN (R 3.2.1)                    
 jsonlite       0.9.19      2015-11-28 CRAN (R 3.2.2)                    
 lazyeval       0.1.10      2015-01-02 CRAN (R 3.2.1)                    
 magrittr       1.5         2014-11-22 CRAN (R 3.2.1)                    
 memoise        1.0.0       2016-01-29 CRAN (R 3.2.3)                    
 mime           0.4         2015-09-03 CRAN (R 3.2.3)                    
 munsell        0.4.2       2013-07-11 CRAN (R 3.2.1)                    
 plyr           1.8.3       2015-06-12 CRAN (R 3.2.0)                    
 R6             2.1.2       2016-01-26 CRAN (R 3.2.3)                    
 RColorBrewer * 1.1-2       2014-12-07 CRAN (R 3.2.1)                    
 Rcpp           0.12.3      2016-01-10 CRAN (R 3.2.3)                    
 rsconnect      0.4.1.11    2016-01-08 Github (rstudio/rsconnect@3034ab8)
 scales         0.3.0.9000  2015-10-09 Github (hadley/scales@7fc502c)    
 shiny        * 0.13.0.9000 2016-02-04 Github (rstudio/shiny@686390c)    
 shinyBS      * 0.61        2015-03-31 CRAN (R 3.2.0)                    
 shinythemes  * 1.0.1       2015-03-03 CRAN (R 3.2.3)                    
 xtable         1.8-0       2015-11-02 CRAN (R 3.2.2)                
```

**Comment by zross** [comment]
Does it work for you in both shiny:: and DT::?

In the branch I just pushed (zr/new_shiny_test) the version with shiny:: works but if I change to DT:: I get the same error. At your recommendation, I was trying to move to DT. 

```r
> devtools::session_info()
Session info ------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, mingw32             
 ui       RStudio (0.99.489)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2016-02-04                  

Packages ----------------------------------------------------------------------------------------
 package      * version     date       source                            
 assertthat     0.1         2013-12-06 CRAN (R 3.2.0)                    
 bitops         1.0-6       2013-08-17 CRAN (R 3.2.0)                    
 colorspace     1.2-6       2015-03-11 CRAN (R 3.2.0)                    
 DBI            0.3.1       2014-09-24 CRAN (R 3.2.0)                    
 devtools       1.9.1       2015-09-11 CRAN (R 3.2.3)                    
 digest         0.6.9       2016-01-08 CRAN (R 3.2.3)                    
 dplyr        * 0.4.3       2015-09-01 CRAN (R 3.2.3)                    
 DT           * 0.1.3       2015-06-18 Github (rstudio/DT@014bdf7)       
 ggplot2      * 2.0.0       2015-12-18 CRAN (R 3.2.3)                    
 gtable         0.1.2       2012-12-05 CRAN (R 3.2.0)                    
 htmltools      0.3         2015-12-29 CRAN (R 3.2.3)                    
 htmlwidgets    0.5         2015-06-21 CRAN (R 3.2.3)                    
 httpuv         1.3.3       2015-08-04 CRAN (R 3.2.1)                    
 httr           0.6.1       2015-01-01 CRAN (R 3.2.0)                    
 jsonlite       0.9.19      2015-11-28 CRAN (R 3.2.3)                    
 lazyeval       0.1.10.9000 2015-09-10 Github (hadley/lazyeval@ecb8dc0)  
 magrittr       1.5         2014-11-22 CRAN (R 3.2.0)                    
 memoise        0.2.1       2014-04-22 CRAN (R 3.2.0)                    
 mime           0.4         2015-09-03 CRAN (R 3.2.2)                    
 munsell        0.4.2       2013-07-11 CRAN (R 3.2.0)                    
 plyr           1.8.3       2015-06-12 CRAN (R 3.2.0)                    
 R6             2.1.2       2016-01-26 CRAN (R 3.2.3)                    
 RColorBrewer * 1.1-2       2014-12-07 CRAN (R 3.2.2)                    
 Rcpp           0.12.3      2016-01-10 CRAN (R 3.2.3)                    
 RCurl          1.95-4.6    2015-04-24 CRAN (R 3.2.0)                    
 scales         0.3.0       2015-08-25 CRAN (R 3.2.3)                    
 shiny        * 0.13.0.9000 2016-02-04 Github (rstudio/shiny@686390c)    
 shinyBS      * 0.62        2015-10-21 Github (ebailey78/shinyBS@67ba9a2)
 shinythemes  * 1.0.1       2015-03-03 CRAN (R 3.2.2)                    
 stringi        1.0-1       2015-10-22 CRAN (R 3.2.3)                    
 stringr        1.0.0       2015-04-30 CRAN (R 3.2.1)                    
 xtable         1.8-0       2015-11-02 CRAN (R 3.2.3)                    
 yaml           2.1.13      2014-06-12 CRAN (R 3.2.0)
```

**Comment by yihui** [comment]
There is an issue with DT, and I just pushed a fix to make it compatible with shiny (`devtools::install_github('rstudio/DT')`). You do not need to use the `DT::` prefix -- you can just `library(DT)` after `library(shiny)` so that DT functions `dataTableOutput()` and `renderDataTable()` override the ones in shiny (you need to be very careful, though, since the order of loading packages is critical if you do not use the `DT::` prefix).

**Comment by zross** [comment]
Seems to be working mostly! When I click on my summary measures tab, the table shows up and I can remove variables but there is some odd behavior that didn't happen before.

1) If you click around and change countries eventually the table doesn't show at all and you can't make any changes to the app. In the console I get a warning of 

`Uncaught TypeError: Cannot read property 'length' of undefined     VM769:588`

2) Occasionally the table header is not at all aligned with the table itself.

Any thoughts on either of these, I really appreciate your work on this.

I updated the online version https://spatial.shinyapps.io/WHO_HETK/


![image](https://cloud.githubusercontent.com/assets/1395177/12828083/b51550a0-cb50-11e5-8205-285fe50ef39d.png)

**Comment by yihui** [comment]
Thanks for bearing with me, and I'm glad we are getting close. I can reproduce both issues. The second one is easier to solve -- just use the DataTables option `autoWidth = TRUE`. You can either set it as a global option `options(DT.options = list(autoWidth = TRUE))`, or set it for individual tables `renderDataTable(..., options = list(autoWidth = TRUE))`.

I'll take a look at the first one soon.

**Comment by zross** [comment]
I really appreciate this. With the width issue I already have autoWidth=TRUE following your note [here](https://rstudio.github.io/DT/options.html). But I am setting two columns to be wider as well with columnDefs. This was working before when the table options were a function and I used shiny::renderDataTables(). The code I use is below, note there are potentially two columnDefs list items but it's seeming to work.


```r
    tableoptions <-  list(pageLength = 100, 
                          dom='frtp', 
                          scrollX = TRUE, 
                          scrollY = '600px',
                          processing = FALSE,
                          scrollCollapse = TRUE,
                          autoWidth = TRUE                          
    )
  
    isnumeric <- unname(which(sapply(theData[,], is.numeric)))
    tableoptions[["columnDefs"]] <- list(list(className = 'dt-center', targets = isnumeric))
    
    
    fullindx1 <- which(names(theData)=="Health indicator full name")
    
    if(length(fullindx1)==1){
      tableoptions[["columnDefs"]] <- append(tableoptions[["columnDefs"]] ,
                                             list(list(width = '200px', targets = fullindx1)))
    }
```

**Comment by yihui** [comment]
I spent some time on the first issue this afternoon, but it seems to be quite difficult to figure out the reason, partly due to the size of this app. I will need to create a minimal reproducible example at some point. Same for the second issue.

I think it is fine for you to stay with `shiny::renderDataTable()` if you do not really need the new features in DT compared to shiny. We are unlikely to deprecate these functions in shiny very soon.

**Comment by zross** [comment]
Sorry about the size of the app! Were you able to tell if these issues are related to DT? You think that using shiny::renderDataTable() will avoid these two issues?

**Comment by yihui** [comment]
I think at least the first issue is related to DT and should not be a problem if you use shiny.

**Comment by zross** [comment]
This is now working, thanks @yihui. I put it back to shiny:: FYI, if you hear of others having trouble with shinyBS modals under the new Shiny I have a solution [here](https://github.com/ebailey78/shinyBS/issues/62)
