### ISSUE TITLE
Functionality: add menu "Select data sources" to summary measures tables, benchmark countries

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#28]

**Comment by zross** [comment]
I'm not seeing "source" in the inequality summary table. This could actually be a small problem with the previous calculation unless I'm missing something. If you look below there are 3 versions of country/year/indic/dimension/measure that occur twice suggesting that these are from different sources. 

```r
             country  year indic         dimension measure     n
               (chr) (int) (chr)             (chr)   (chr) (int)
1 Dominican Republic  2002 fullv Geographic region      rd     2
2 Dominican Republic  2002 fullv Geographic region      rr     2
3             Gambia  2005  bcgv Geographic region      rd     2
4             Gambia  2005  bcgv Geographic region      rr     2
5             Zambia  2001   ors Geographic region      rd     2
6             Zambia  2001   ors Geographic region      rr     2
```

**Comment by zross** [comment]
Given what I wrote above I assume that I should adjust the calculations of the `inequals` table correct? It should have source. And then I can add source buttons.

**Comment by WHOequity** [comment]
Yes, the inequals table should have the source in it as well. The tabs displaying summary measures should have a source selection menu in the left panel.

Regarding the data above: Data for each country/year/indicator/dimension combination comes from only one source each (DHS for Dominican Republic and Zambia, MICS for Gambia). But two different summary measures are calculated (RD and RR).
