### ISSUE TITLE
Design: Logo should be blue

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#4]
@WHOequity do you have a blue logo. I can edit the black one if necessary but if you have a blue one that would be great.

**Comment by WHOequity** [comment]
Yes, we do have a blue logo. Can I send this through GitHub?

**Comment by WHOequity** [comment]
![who-en-c-h](https://cloud.githubusercontent.com/assets/13563065/9996031/6705356e-6085-11e5-83c3-52a8fd10f912.png)
![who-en-c-h](https://cloud.githubusercontent.com/assets/13563065/9996032/670b820c-6085-11e5-8702-37d5c444637e.jpg)

**Comment by zross** [comment]
got it

**Comment by zross** [comment]
Blue probably doesn't work if we have a blue background. Take a look at what I have up now and see if the white works.

**Comment by WHOequity** [comment]
White is good. Is the logo you have ok, or do you need another version?

**Comment by zross** [comment]
I don't need another version if you're happy with what I added. If so, can you close?
