### ISSUE TITLE
Functionality: set default selection of benchmark countries to no countries

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#44]
see PDF

**Comment by zross** [comment]
This is easy but are you sure? This requires the user to make selections before seeing plots etc. I think it would be better to choose a few countries as good starting examples and have those pre-selected. That way a user can play around with tabs and they will show up with plots. Right now I have Afghanistan, Belize and Liberia being compare to Armenia.

**Comment by WHOequity** [comment]
Not sure. Will get back to you on this.

**Comment by zross** [comment]
@WHOequity what do you think on this one?

**Comment by WHOequity** [comment]
Can we change the default selection to be the same income group and WHO region as the selected country of interest (i.e. all countries from that same income group and WHO region are shown)?

**Comment by zross** [comment]
We can use what you want. Can you tell me what you want for the focus country and benchmark countries. What about default -- first view for indicator, dimension etc?

**Comment by zross** [comment]
In #89 you mentioned:

The default selection should be all countries from the same income group and WHO region as the selected country of interest (i.e. the income group filter displays the same income group, the WHO region filter the same region and the country menu all the relevant countries).

What do you want the default selected country, indicator, dimension etc to be. then I can match the region etc.
