### ISSUE TITLE
Functionality: remove table from benchmark countries

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#48]
see PDF

**Comment by zross** [comment]
Are you sure about this, I like the table, what would you have instead -- blank? Also, it makes for an easy way for your users to download data for multiple countries. I'm leaving it for now unless you feel strongly that it should go.

**Comment by WHOequity** [comment]
Users should also be able to download data for multiple countries from the other two tabs: disaggregated data from the disaggregated data (graphs) tab and summary measure data from the summary measures (graphs) tab. 

Not sure about the table. Will discuss and get back to you on this.

**Comment by zross** [comment]
Did you make a decision on this? If you want to keep the table please close this issue, if not let me know.

**Comment by WHOequity** [comment]
Yes, please keep the table and rename the tab to "Disaggregated data (tables)". 

In addition, we'd also like a tab for "Summary measures (tables)" showing the summary measures for all benchmark countries in a table format.
