### ISSUE TITLE
Speed: bottlenecks

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#68]
getFilteredCountries is very slow to grab the distinct countries

**Comment by zross** [comment]
In the plots and tables tabs there are repeated calls to datasetInput() which requires a new query each time.

**Comment by zross** [comment]
I put a print statement in all the items so far and equityCountry is definitely the slowest and this is what calls getFilteredCountries

**Comment by zross** [comment]
The getFiltered functions can use pre-generated tables so I pre-calculated one for countries and one for years and this is much faster!

**Comment by WHOequity** [comment]
Great! Does this have any other implications?

**Comment by zross** [comment]
See #82
