### ISSUE TITLE
Bug: possible bugs in original

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#75]
in `getHETKdata` I'm not seeing where the query looks at source

In queries with `MAX` and `COUNT` against database, I'm not seeing a `GROUP BY` statement so I'm not sure it's doing the query correctly.

**Comment by zross** [comment]
Looks like the inequals table should have source but does not.

**Comment by zross** [comment]
See #93 there is an error if the data has no estimate and you click on plot.

**Comment by WHOequity** [comment]
I'm not sure I understand this correctly. 

Yes, our database with the disaggregated data has missing observations. Therefore, summary measures are (or should be) only calculated for country/year/indicator/dimension combinations where data are available for all required subgroups.

I don't know how the inequals table is created exactly. It should contain the source as well. If not, this is a bug.

**Comment by WHOequity** [comment]
Please feel free to close, if you have addressed this.
