### ISSUE TITLE
Functionality: default choices and behavior

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#77]
I'm opening a new thread related to #42 to focus on default behavior. I feel somewhat strongly about three things:

1) I think it's more satisfying to users if data shows up right away -- no fetch data on any page. So I think we should have a default for when the users open the app. Right now I've got this at the first selection in each of the items. This is easy to change, though.

2) I think that a user should not be required to click on one tab first. It's confusing, I didn't even realize this was required at first.

3) I think that we should give uses maximum flexibility and not require them to move from one tab to another in order to simply change, for example, the indicator. 

So I'm proposing that all pages have default values and that users can click to any tab at any time and users can make key changes (to country, indicator etc) on any tab.

OK?

**Comment by WHOequity** [comment]
Yes, this all sounds reasonable. Will all tabs update automatically according to what has been selected in a (any) tab? This is quite important to us.

**Comment by zross** [comment]
Yes, tabs will update automatically, though we will need to discuss how this affects "compare" since the compare section only allows one indicator etc. I likely will choose the first indicator selected but I'll ask when I reach that point.

**Comment by WHOequity** [comment]
Ok.
