### ISSUE TITLE
Cleaning: are core and full indicators the same

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#79]
@WHOequity  Right now the full and core indicators look the same. Is this true?

**Comment by WHOequity** [comment]
I believe so. I am wondering if this was intended to be used by us in order to be able to limit the number of indicators displayed. We have never used this feature, though (and maybe never will if you suggest another mechanism for us to limit/update the data).

**Comment by zross** [comment]
OK, for now, I'll leave that in, but won't touch it.
