### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#81]
@WHOequity The active version on shinyapps has not been completely re-hooked up yet. But I removed the app's dependency on SQLite which speeds up things a ton and also reduces the size of the data from 80mb or so down to <15mb. There are quite a few advantages to bringing the full dataset into memory. Mostly speed.

Please keep in mind that only the explore/disaggregated pages are fully hooked up to the selectors, there will be errors on the other pages. Test it out and let me know what you think of speed on the main page.

**Comment by WHOequity** [comment]
Agree. Seems to be a lot quicker!

**Comment by WHOequity** [comment]
What exactly do you mean by removing the app's dependency on SQLite? Does this have any other implications?

**Comment by zross** [comment]
@WHOequity put up a major updated. Changed theme to cerulean. The app is much faster and I believe that all the selection menus are remembering the selections between tabs with one exception -- if you click to compare first, make a change and then go back to explore it won't remember but working on this.

**Comment by WHOequity** [comment]
Great! Much prefer this theme. Looks lighter and cleaner. 

I only noticed, that it's hard to tell which menu/tab you are in. Is it possible to make this clearer in both the top menu (e.g. by making the titles more bold or highlight in a different colour) and in the tabs selection (the boxed line around the tab title seems insufficient)?

**Comment by WHOequity** [comment]
The tabs work together much better. Also came across the compare inequality issue. But it doesn't seem to happen every time. Will do some more testing.

**Comment by WHOequity** [comment]
There still seems to be an issue with the selection menu: The compare inequality tab doesn't remember the selections made under explore inequality when you first move from explore inequality to compare inequality and vice versa.

**Comment by zross** [comment]
This is related to #92 seems not to remember selections that first time. I'll look into it. In the meantime I'm closing this issue and moving your comment over.
