### ISSUE TITLE
Functionality: remove dependency on RSQlite

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#82]
much of the speed issues are associated with multiple queries to SQLite which is an external database. I don't know why your previous developer used SQLite but I'm guessing one of two reasons:

1) He wasn't sure how to make the data "global" -- so that all functions all tabs could access the data anytime.
2) He thought there would be memory issues.

With number 1, I've made the data global, this is not a problem. In terms of memory issues:

R reads data into memory all at once. So if you have a giant dataset, the computer that R is on may not have enough memory to read in all at once and this is where you might use an external database like SQLite. In our case, the data is not big at all -- 200k rows or so -- so I don't see any reason for this.

Implications are: much, much faster because the data resides in memory, also much cleaner because all the data is available and we don't need to write different queries each time we need new data.

The only possible negative is if computers at the workshop are incredibly old with very little memory they would not be able to read in the data. But the data is just 30mb in memory (the file is <10mb) so I very much doubt this would be an issue. And if these computers are so old with so little memory they would choke on the SQLite queries anyway.

**Comment by WHOequity** [comment]
Ok, thanks.
