### ISSUE TITLE
If time permits: limit user choices based on other choices

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#83]
Right now the selections are not being clipped based on previous selections. So, for example, Armenia does not have 2010 place of residence but it is still a choice.

**Comment by WHOequity** [comment]
Yes, not all sources, years, indicators and dimensions are available for all countries. At the moment, only the selection menu for years adapts to the country selection (such that only the years for which data are available are shown), while the selection menus for sources, indicators and dimensions don't adapt.

Agreed that it may be good if all selection menus adapted to the selected country. Not sure, though, if they can/should all depend on each other as well? This could become confusing.

**Comment by WHOequity** [comment]
We're happy with the way the selection menu works now: The user can select from all available variable combinations, but an error message appears if the selected combination is not available for the country of choice.
