### ISSUE TITLE
Functionality: how to handle income/who regions

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#89]
@WHOequity how do you want to handle situations where the user has already selected a few countries and then selects a WHO region or income group that does not match with current selections. Options:

1) leave selections as is BUT change the selection menu for new choices
2) Only keep current selections that match the region/income selections. In many cases this would mean no selections.

2b) we could apply the second item above but add an additional caveat that if the region/income selection removes all current choices then we could choose the first country that matches the region/income group

For now I'm using number 1

**Comment by WHOequity** [comment]
It would probably be better if the filter menus were the other way around, i.e. if users could first filter by country income group and WHO region and then select the countries. Only those countries matching the filter would be available for selection.

**Comment by zross** [comment]
@WHOequity how are you feeling about how it's working now? If you're satisfied can you close?

**Comment by WHOequity** [comment]
The order of selection menus is good. The default selection should be all countries from the same income group and WHO region as the selected country of interest (i.e. the income group filter displays the same income group, the WHO region filter the same region and the country menu all the relevant countries).

**Comment by zross** [comment]
opening new issue on defaults and closing this one

**Comment by zross** [comment]
@WHOequity I am not clear on what you want here. In #145 you wanted middle-income, south-east Asia. Indonesia is the selected focus country and the selected benchmark countries are all the other countries in middle-income south-east Asia. This is clear.

But what do you want to happen in the following situation:

1) User changes main selected country from Indonesia to Bhutan. What I was assuming is that we remove Bhutan from selected benchmark countries and add Indonesia to the POSSIBLE choices but do not automatically add it as a selected benchmark country.

**Comment by WHOequity** [comment]
No, I think it's perfect as it is now (i.e. in the above mentioned case, if the user changes from Indonesia to Bhutan, then Indonesia is automatically added as a benchmark country).
