### ISSUE TITLE
Functionality: default graph size

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#94]
@WHOequity how strongly do you feel about allowing the user to adjust the plot dimensions. This seems like clutter to me, instead I'd prefer to base the size of the plot on the size of the window available and have it change on the fly.

I've updated the app to do this on the Explore disaggregated plot. See what you think

**Comment by WHOequity** [comment]
Yes, agreed. Much better! Please implement for all graphs. 

What size will the graph be when you download it?

**Comment by zross** [comment]
I've made it so that the size can be specified in the download
