### ISSUE TITLE
Error when "Flag" is added to Explore inequality - Disaggregated data (tables)

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#95]
When "Flag" is selected as an additional column from the "Select table content" selection menu, an error message appears (undefined columns selected).

**Comment by WHOequity** [comment]
Also, the disaggregated data (graphs) don't show, when "Flag" is selected in the disaggregated data (tables) tab.

**Comment by zross** [comment]
capitalization issue. Fixed, not yet uploaded.
