### ISSUE TITLE
Column "ccode" should be dropped from Explore inequality - Summary measures (tables)

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#96]
This is new I think!? Should be dropped.

**Comment by zross** [comment]
I'm not seeing it now, must have been an interim version.

**Comment by WHOequity** [comment]
No, I'm still seeing it.

**Comment by WHOequity** [comment]
![screenshot - table - 2015-10-13](https://cloud.githubusercontent.com/assets/13563065/10448879/185734c8-7190-11e5-8efd-bbe4eea21aa8.png)

**Comment by zross** [comment]
Oops, sorry, I misunderstood where you were seeing it. It has now been removed. Please close this issue when you agree :)

**Comment by WHOequity** [comment]
Perfect, yes, thanks.
