### ISSUE TITLE
Add buttons to download data displayed in graphs

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#97]
All data displayed in graphs, should also be available for direct download in a .csv format. 

See also PDF file and issue #48.

**Comment by zross** [comment]
Do you also want this in the Explore Inequality tabs?

**Comment by WHOequity** [comment]
Yes. Is it possible to have the download graph and download data buttons in the same line (rather than one below the other)?

**Comment by zross** [comment]
Yes. There was an issue I was seeing when they were on the same line so I put it aside for the moment to complete required things.

**Comment by zross** [comment]
added new issue for inline #107 but closing this
