### ISSUE TITLE
Change order of selection menus in Compare inequality tabs

### ISSUE THREAD

**Issue by WHOequity** [WHOequity/who-heat#99]
The "Filter benchmark countries by income group/WHO Region" selection menus should appear above the "Select benchmark countries" menu, if possible? The countries available for selection int the "Select benchmark countries" menu are then limited to the selection income group and WHO Region.

**Comment by WHOequity** [comment]
See issue #89.

**Comment by WHOequity** [comment]
In the Summary measures (graphs) tab, the "Select summary measure" menu should appear above the line and benchmark options (same as in the Explore inequality - Summary measures (graphs) tab).

**Comment by zross** [comment]
Can you confirm this has what you like and close this issue?

**Comment by WHOequity** [comment]
Yes, perfect! Can we change the default selection to the same income group and WHO region as the country of interest (i.e. the group filter shows the same income group as the country of interest, the region filter the same WHO region as the country of interest and all countries from that same group and region are selected)?

**Comment by WHOequity** [comment]
Currently there is an issue that when you unselect all benchmark countries and then select any income group or WHO region, the countries Afghanistan, Belize and Liberia are added automatically to the selection menu for benchmark countries (regardless of what income group or WHO region has been selected).

**Comment by zross** [comment]
#130 I opened a new issue for the bug and I'm closing this as it solves this issue.
